/**
 * Comprehensive Technology Tree
 * 
 * All 70+ breakthrough technologies with prerequisites, costs, and effects.
 * Based on allBreakthroughTech.md catalog (October 2025)
 */

export interface TechDefinition {
  id: string;
  name: string;
  description: string;
  category: 'alignment' | 'social' | 'medical' | 'energy' | 'climate' | 'ocean' | 'freshwater' | 'agriculture' | 'pollution';
  status: 'deployed_2025' | 'unlockable' | 'future';
  
  // Unlock conditions
  prerequisites: string[];
  minAICapability?: number;
  minEconomicStage?: number;
  minMonth?: number;
  
  // Research and deployment
  researchMonthsRequired: number;
  researchCost: number;  // $M total research cost
  deploymentCost: number;  // $M total deployment cost
  deploymentMonthsRequired: number;
  
  // Current deployment (for deployed_2025 tech)
  deploymentLevel: number;  // 0-1
  
  // Effects (when fully deployed)
  effects: Record<string, number>;
}

/**
 * All breakthrough technologies
 */
const ALL_TECH: TechDefinition[] = [
  // ============================================================================
  // TIER 0: DEPLOYED 2025 (11 technologies)
  // ============================================================================
  
  // Alignment & Safety (3)
  {
    id: 'rlhf_basic',
    name: 'Basic RLHF',
    description: 'Reinforcement Learning from Human Feedback - surface alignment, reduces toxicity',
    category: 'alignment',
    status: 'deployed_2025',
    prerequisites: [],
    researchMonthsRequired: 0,
    researchCost: 0,
    deploymentCost: 100,
    deploymentMonthsRequired: 0,
    deploymentLevel: 0.95,
    effects: {
      alignmentBonus: 0.05,
    },
  },
  {
    id: 'mech_interp_basic',
    name: 'Basic Mechanistic Interpretability',
    description: 'Sparse autoencoders, probes - understanding AI internals',
    category: 'alignment',
    status: 'deployed_2025',
    prerequisites: [],
    researchMonthsRequired: 0,
    researchCost: 0,
    deploymentCost: 150,
    deploymentMonthsRequired: 0,
    deploymentLevel: 0.15,
    effects: {
      sleeperDetectionBonus: 0.03,
    },
  },
  {
    id: 'adversarial_eval',
    name: 'Adversarial Evaluation',
    description: 'Red-teaming, safety testing - finding AI failure modes',
    category: 'alignment',
    status: 'deployed_2025',
    prerequisites: [],
    researchMonthsRequired: 0,
    researchCost: 0,
    deploymentCost: 80,
    deploymentMonthsRequired: 0,
    deploymentLevel: 0.40,
    effects: {
      alignmentBonus: 0.02,
      sleeperDetectionBonus: 0.01,
    },
  },
  
  // Climate (3)
  {
    id: 'de_extinction',
    name: 'De-Extinction & Rewilding',
    description: 'Colossal Biosciences - woolly mammoth, thylacine restoration',
    category: 'climate',
    status: 'deployed_2025',
    prerequisites: [],
    researchMonthsRequired: 0,
    researchCost: 0,
    deploymentCost: 500,
    deploymentMonthsRequired: 0,
    deploymentLevel: 0.01,
    effects: {
      biodiversityBonus: 0.005,
    },
  },
  {
    id: 'direct_air_capture',
    name: 'Advanced Direct Air Capture',
    description: 'Climeworks Mammoth - 36,000 tons CO2/year capture',
    category: 'climate',
    status: 'deployed_2025',
    prerequisites: [],
    researchMonthsRequired: 0,
    researchCost: 0,
    deploymentCost: 1000,
    deploymentMonthsRequired: 0,
    deploymentLevel: 0.02,
    effects: {
      carbonRemoval: 0.01,
    },
  },
  {
    id: 'ai_pollution_remediation',
    name: 'AI-Optimized Pollution Remediation',
    description: 'US DOE ML frameworks for cleanup optimization',
    category: 'pollution',
    status: 'deployed_2025',
    prerequisites: [],
    researchMonthsRequired: 0,
    researchCost: 0,
    deploymentCost: 300,
    deploymentMonthsRequired: 0,
    deploymentLevel: 0.10,
    effects: {
      pollutionReduction: 0.02,
    },
  },
  
  // Social (1)
  {
    id: 'collective_purpose_networks',
    name: 'Collective Purpose Networks',
    description: 'Harvard Making Caring Common - meaning infrastructure',
    category: 'social',
    status: 'deployed_2025',
    prerequisites: [],
    researchMonthsRequired: 0,
    researchCost: 0,
    deploymentCost: 200,
    deploymentMonthsRequired: 0,
    deploymentLevel: 0.15,
    effects: {
      meaningReduction: 0.03,
      socialConnectionBonus: 0.02,
    },
  },
  
  // Medical (2)
  {
    id: 'ai_diagnostics',
    name: 'AI Diagnostics',
    description: 'PathAI, Google Health - automated disease detection',
    category: 'medical',
    status: 'deployed_2025',
    prerequisites: [],
    researchMonthsRequired: 0,
    researchCost: 0,
    deploymentCost: 400,
    deploymentMonthsRequired: 0,
    deploymentLevel: 0.25,
    effects: {
      healthcareBonus: 0.05,
      mortalityReduction: 0.01,
    },
  },
  {
    id: 'mrna_vaccines',
    name: 'mRNA Vaccine Platforms',
    description: 'Moderna, BioNTech - rapid vaccine development',
    category: 'medical',
    status: 'deployed_2025',
    prerequisites: [],
    researchMonthsRequired: 0,
    researchCost: 0,
    deploymentCost: 800,
    deploymentMonthsRequired: 0,
    deploymentLevel: 0.40,
    effects: {
      pandemicResponse: 0.30,
      mortalityReduction: 0.02,
    },
  },
  
  // Energy (2)
  {
    id: 'solar_4th_gen',
    name: '4th Generation Solar',
    description: 'Perovskite tandem cells, Oxford PV - 30% efficiency',
    category: 'energy',
    status: 'deployed_2025',
    prerequisites: [],
    researchMonthsRequired: 0,
    researchCost: 0,
    deploymentCost: 5000,
    deploymentMonthsRequired: 0,
    deploymentLevel: 0.08,
    effects: {
      cleanEnergyPercentage: 0.08,
      fossilDependenceReduction: 0.05,
    },
  },
  {
    id: 'offshore_wind',
    name: 'Offshore Wind',
    description: 'Hornsea, Dogger Bank - 10+ GW installations',
    category: 'energy',
    status: 'deployed_2025',
    prerequisites: [],
    researchMonthsRequired: 0,
    researchCost: 0,
    deploymentCost: 8000,
    deploymentMonthsRequired: 0,
    deploymentLevel: 0.12,
    effects: {
      cleanEnergyPercentage: 0.12,
      fossilDependenceReduction: 0.08,
    },
  },
  
  // ============================================================================
  // TIER 1: PLANETARY BOUNDARY CRISIS TECH (18 technologies)
  // ============================================================================
  
  // Phosphorus Depletion (4)
  {
    id: 'struvite_recovery',
    name: 'Struvite Recovery',
    description: 'Recover 98.3% of phosphorus from wastewater as struvite crystals',
    category: 'agriculture',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 1.5,
    minEconomicStage: 2.5,
    researchMonthsRequired: 24,
    researchCost: 500,
    deploymentCost: 150000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      phosphorusRecovery: 0.35,
      pollutionReduction: 0.025,
    },
  },
  {
    id: 'soil_p_optimization',
    name: 'Dynamic Soil P Optimization',
    description: 'AI field-level optimization unlocking 6.6 Tg/year legacy soil P',
    category: 'agriculture',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.0,
    researchMonthsRequired: 18,
    researchCost: 800,
    deploymentCost: 80000,
    deploymentMonthsRequired: 36,
    deploymentLevel: 0,
    effects: {
      phosphorusEfficiency: 0.30,
      miningDemandReduction: 0.35,
    },
  },
  {
    id: 'p_efficient_cultivars',
    name: 'P-Efficient Cultivars',
    description: 'Deep roots, P-solubilizing bacteria, mycorrhizal networks',
    category: 'agriculture',
    status: 'unlockable',
    prerequisites: ['soil_p_optimization'],
    minAICapability: 2.5,
    researchMonthsRequired: 36,
    researchCost: 1200,
    deploymentCost: 120000,
    deploymentMonthsRequired: 60,
    deploymentLevel: 0,
    effects: {
      phosphorusEfficiency: 0.25,
      miningDemandReduction: 0.20,
      biodiversityBonus: 0.01,
    },
  },
  {
    id: 'circular_food_systems',
    name: 'Circular Food Systems',
    description: 'Close the loop - waste recovery, plant-based diets - 50% total efficiency',
    category: 'agriculture',
    status: 'unlockable',
    prerequisites: ['struvite_recovery'],
    minEconomicStage: 3.0,
    researchMonthsRequired: 60,
    researchCost: 2000,
    deploymentCost: 200000,
    deploymentMonthsRequired: 120,
    deploymentLevel: 0,
    effects: {
      phosphorusEfficiency: 0.30,
      phosphorusRecovery: 0.20,
      foodSecurityBonus: 0.03,
    },
  },
  
  // Freshwater Depletion (4)
  {
    id: 'desalination_advanced',
    name: 'Advanced Desalination',
    description: 'Energy-efficient reverse osmosis with graphene membranes',
    category: 'freshwater',
    status: 'unlockable',
    prerequisites: ['solar_4th_gen'],
    minAICapability: 1.8,
    minEconomicStage: 2.5,
    researchMonthsRequired: 12,
    researchCost: 2000,
    deploymentCost: 300000,
    deploymentMonthsRequired: 36,
    deploymentLevel: 0,
    effects: {
      freshwaterSupply: 0.40,
      dayZeroRiskReduction: 0.60,
    },
  },
  {
    id: 'atmospheric_water_harvest',
    name: 'Atmospheric Water Harvesting',
    description: 'Solar-powered extraction using zeolites - SOURCE Global',
    category: 'freshwater',
    status: 'unlockable',
    prerequisites: ['desalination_advanced', 'solar_4th_gen'],
    minAICapability: 2.5,
    researchMonthsRequired: 24,
    researchCost: 1500,
    deploymentCost: 150000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      freshwaterSupply: 0.20,
      droughtResilience: 0.30,
    },
  },
  {
    id: 'aquifer_mapping_ai',
    name: 'Global Aquifer Mapping',
    description: 'GRACE satellites + ML prediction of groundwater levels',
    category: 'freshwater',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.0,
    researchMonthsRequired: 18,
    researchCost: 800,
    deploymentCost: 80000,
    deploymentMonthsRequired: 24,
    deploymentLevel: 0,
    effects: {
      waterManagementBonus: 0.25,
      aquiferProtection: 0.15,
    },
  },
  {
    id: 'drought_resistant_crops',
    name: 'Drought-Resistant Crops',
    description: 'CAM photosynthesis, deep roots - CRISPR engineering',
    category: 'agriculture',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    researchMonthsRequired: 36,
    researchCost: 1000,
    deploymentCost: 120000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      waterEfficiency: 0.40,
      cropYieldBonus: 0.15,
      droughtResilience: 0.30,
    },
  },
  
  // Ocean Health (3)
  {
    id: 'ocean_alkalinity_enhancement',
    name: 'Ocean Alkalinity Enhancement',
    description: 'Olivine dissolution - counteracts acidification',
    category: 'ocean',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    minEconomicStage: 3.0,
    minMonth: 24,
    researchMonthsRequired: 36,
    researchCost: 3000,
    deploymentCost: 250000,
    deploymentMonthsRequired: 60,
    deploymentLevel: 0,
    effects: {
      oceanPHBonus: 0.30,
      coralSurvival: 0.40,
      carbonRemoval: 0.10,
    },
  },
  {
    id: 'coral_restoration_advanced',
    name: 'Advanced Coral Restoration',
    description: 'Heat-tolerant strains, 3D printing, micro-fragmentation',
    category: 'ocean',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.0,
    researchMonthsRequired: 24,
    researchCost: 800,
    deploymentCost: 100000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      coralCoverage: 0.25,
      biodiversityBonus: 0.05,
      fisheryBonus: 0.10,
    },
  },
  {
    id: 'artificial_upwelling',
    name: 'Artificial Upwelling',
    description: 'Wave-powered pumps bring nutrients - RISKY',
    category: 'ocean',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 3.0,
    minEconomicStage: 3.5,
    minMonth: 48,
    researchMonthsRequired: 48,
    researchCost: 5000,
    deploymentCost: 400000,
    deploymentMonthsRequired: 72,
    deploymentLevel: 0,
    effects: {
      fisheryBonus: 0.30,
      oxygenBonus: 0.15,
      riskDeadZones: 0.20,  // RISKY - can make things worse
    },
  },
  
  // Pollution (4)
  {
    id: 'pfas_remediation',
    name: 'PFAS Remediation',
    description: 'Electrochemical destruction, supercritical water oxidation',
    category: 'pollution',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.0,
    researchMonthsRequired: 24,
    researchCost: 1500,
    deploymentCost: 180000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      pfasReduction: 0.70,
      healthBonus: 0.05,
      pollutionReduction: 0.10,
    },
  },
  {
    id: 'plastic_eating_enzymes',
    name: 'Plastic-Eating Enzymes',
    description: 'PETase, MHETase - break down PET in 24 hours',
    category: 'pollution',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    researchMonthsRequired: 30,
    researchCost: 1200,
    deploymentCost: 150000,
    deploymentMonthsRequired: 60,
    deploymentLevel: 0,
    effects: {
      plasticReduction: 0.50,
      oceanHealthBonus: 0.10,
      pollutionReduction: 0.15,
    },
  },
  {
    id: 'green_chemistry',
    name: 'Green Chemistry',
    description: 'Benign-by-design chemicals, biomimetic catalysts',
    category: 'pollution',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.0,
    minEconomicStage: 3.0,
    researchMonthsRequired: 36,
    researchCost: 2000,
    deploymentCost: 200000,
    deploymentMonthsRequired: 72,
    deploymentLevel: 0,
    effects: {
      newPollutionPrevention: 0.60,
      healthBonus: 0.08,
    },
  },
  {
    id: 'pesticide_alternatives',
    name: 'Pesticide Alternatives',
    description: 'RNA interference, CRISPR precision, beneficial insects',
    category: 'agriculture',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    researchMonthsRequired: 30,
    researchCost: 1000,
    deploymentCost: 120000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      pollinatorPopulation: 0.50,
      biodiversityBonus: 0.08,
      cropYieldBonus: 0.05,
    },
  },
  
  // Novel Entities (3)
  {
    id: 'microplastic_capture',
    name: 'Microplastic Capture',
    description: 'Electrocoagulation, magnetic separation - ocean cleanup',
    category: 'pollution',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.0,
    researchMonthsRequired: 24,
    researchCost: 1500,
    deploymentCost: 200000,
    deploymentMonthsRequired: 60,
    deploymentLevel: 0,
    effects: {
      microplasticReduction: 0.40,
      oceanHealthBonus: 0.10,
      marineLifeBonus: 0.05,
    },
  },
  {
    id: 'endocrine_disruptor_removal',
    name: 'Endocrine Disruptor Removal',
    description: 'Advanced water treatment - remove hormone-mimicking chemicals',
    category: 'pollution',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.0,
    researchMonthsRequired: 24,
    researchCost: 1200,
    deploymentCost: 150000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      endocrineDisruptorReduction: 0.60,
      fertilityBonus: 0.10,
      healthBonus: 0.05,
    },
  },
  {
    id: 'nanomaterial_safety',
    name: 'Nanomaterial Safety Protocols',
    description: 'AI toxicity prediction, containment, lifecycle management',
    category: 'pollution',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    researchMonthsRequired: 30,
    researchCost: 1000,
    deploymentCost: 100000,
    deploymentMonthsRequired: 36,
    deploymentLevel: 0,
    effects: {
      nanomaterialRisk: -0.70,
      healthBonus: 0.03,
    },
  },
  
  // ============================================================================
  // TIER 2: MAJOR MITIGATIONS (22 technologies)
  // ============================================================================
  
  // Social (8)
  {
    id: 'enhanced_ubi',
    name: 'Enhanced UBI Systems',
    description: 'Adaptive payments, purpose infrastructure, local currencies',
    category: 'social',
    status: 'unlockable',
    prerequisites: [],
    minEconomicStage: 2.5,
    researchMonthsRequired: 18,
    researchCost: 500,
    deploymentCost: 50000,
    deploymentMonthsRequired: 36,
    deploymentLevel: 0,
    effects: {
      unemploymentSupport: 0.40,
      meaningReduction: 0.10,
      socialStabilityBonus: 0.15,
    },
  },
  {
    id: 'purpose_networks_advanced',
    name: 'Advanced Purpose Networks',
    description: 'AI matching, project coordination, skill development',
    category: 'social',
    status: 'unlockable',
    prerequisites: ['collective_purpose_networks'],
    minAICapability: 2.0,
    researchMonthsRequired: 24,
    researchCost: 800,
    deploymentCost: 80000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      meaningReduction: 0.20,
      socialConnectionBonus: 0.15,
      volunteerResearchBonus: 0.30,
    },
  },
  {
    id: 'ai_community_matching',
    name: 'AI Community Matching',
    description: 'Connect people with shared values and complementary skills',
    category: 'social',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    researchMonthsRequired: 18,
    researchCost: 400,
    deploymentCost: 40000,
    deploymentMonthsRequired: 24,
    deploymentLevel: 0,
    effects: {
      socialConnectionBonus: 0.25,
      meaningReduction: 0.08,
      mentalHealthBonus: 0.10,
    },
  },
  {
    id: 'mental_health_ai',
    name: 'AI Mental Health Support',
    description: 'CBT chatbots, crisis detection, personalized therapy',
    category: 'medical',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.0,
    researchMonthsRequired: 24,
    researchCost: 600,
    deploymentCost: 60000,
    deploymentMonthsRequired: 36,
    deploymentLevel: 0,
    effects: {
      mentalHealthBonus: 0.30,
      meaningReduction: 0.10,
      suicideReduction: 0.40,
    },
  },
  {
    id: 'creative_empowerment_tools',
    name: 'Creative Empowerment Tools',
    description: 'AI art, music, writing assistants - democratize creation',
    category: 'social',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    researchMonthsRequired: 18,
    researchCost: 300,
    deploymentCost: 30000,
    deploymentMonthsRequired: 24,
    deploymentLevel: 0,
    effects: {
      meaningReduction: 0.12,
      socialConnectionBonus: 0.08,
      mentalHealthBonus: 0.05,
    },
  },
  {
    id: 'democratic_ai_governance',
    name: 'Democratic AI Governance',
    description: 'Participatory decision-making, transparent algorithms, collective input',
    category: 'social',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    minEconomicStage: 3.0,
    researchMonthsRequired: 30,
    researchCost: 1000,
    deploymentCost: 100000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      trustBonus: 0.25,
      socialStabilityBonus: 0.15,
      paranoiaReduction: 0.10,
    },
  },
  {
    id: 'ai_power_efficiency_communication',
    name: 'AI Power Efficiency Communication',
    description: 'Transparent reporting of AI energy efficiency gains, public education on compute benefits',
    category: 'social',
    status: 'unlocked', // Already available in 2025 (IEA, Epoch AI, Stanford AI Index data exists)
    prerequisites: [],
    minAICapability: 1.0,
    researchMonthsRequired: 0, // Already researched
    researchCost: 0,
    deploymentCost: 10000, // Low cost - mostly communication and reporting
    deploymentMonthsRequired: 12,
    deploymentLevel: 0.05, // 5% initial deployment in 2025 (limited public awareness)
    effects: {
      trustBonus: 0.01, // +1% trust/month when demonstrating efficiency gains
      publicAwarenessBonus: 0.02, // Increases public understanding of AI benefits
      paranoiaReduction: 0.02, // Transparency reduces fear
    },
    citations: [
      'IEA Energy Efficiency 2024',
      'Epoch AI Compute Trends',
      'Stanford AI Index 2024',
    ],
  },
  {
    id: 'education_personalization',
    name: 'Personalized Education',
    description: 'AI tutors, adaptive curricula, lifelong learning',
    category: 'social',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.0,
    researchMonthsRequired: 24,
    researchCost: 800,
    deploymentCost: 100000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      educationBonus: 0.40,
      skillDevelopment: 0.30,
      meaningReduction: 0.08,
    },
  },
  {
    id: 'local_resilience_networks',
    name: 'Local Resilience Networks',
    description: 'Community preparedness, mutual aid, distributed resources',
    category: 'social',
    status: 'unlockable',
    prerequisites: [],
    minEconomicStage: 2.5,
    researchMonthsRequired: 18,
    researchCost: 400,
    deploymentCost: 50000,
    deploymentMonthsRequired: 36,
    deploymentLevel: 0,
    effects: {
      crisisResilience: 0.30,
      socialConnectionBonus: 0.15,
      localEconomyBonus: 0.10,
    },
  },
  
  // Alignment (5)
  {
    id: 'scalable_oversight',
    name: 'Scalable Oversight',
    description: 'AI systems that can oversee and correct other AIs',
    category: 'alignment',
    status: 'unlockable',
    prerequisites: ['rlhf_basic', 'mech_interp_basic'],
    minAICapability: 2.5,
    researchMonthsRequired: 36,
    researchCost: 5000,
    deploymentCost: 3000,
    deploymentMonthsRequired: 24,
    deploymentLevel: 0,
    effects: {
      alignmentBonus: 0.15,
      sleeperDetectionBonus: 0.10,
    },
  },
  {
    id: 'mech_interp_advanced',
    name: 'Advanced Mechanistic Interpretability',
    description: 'Full circuit analysis, causal interventions, goal extraction',
    category: 'alignment',
    status: 'unlockable',
    prerequisites: ['mech_interp_basic', 'scalable_oversight'],
    minAICapability: 3.0,
    researchMonthsRequired: 48,
    researchCost: 8000,
    deploymentCost: 5000,
    deploymentMonthsRequired: 36,
    deploymentLevel: 0,
    effects: {
      alignmentBonus: 0.20,
      sleeperDetectionBonus: 0.25,
      deceptionDetection: 0.30,
    },
  },
  {
    id: 'defensive_ai',
    name: 'Defensive AI Systems',
    description: 'Automated threat detection, sandboxing, containment',
    category: 'alignment',
    status: 'unlockable',
    prerequisites: ['scalable_oversight'],
    minAICapability: 3.0,
    researchMonthsRequired: 36,
    researchCost: 6000,
    deploymentCost: 4000,
    deploymentMonthsRequired: 30,
    deploymentLevel: 0,
    effects: {
      sleeperDetectionBonus: 0.30,
      threatContainment: 0.40,
      cyberDefenseBonus: 0.25,
    },
  },
  {
    id: 'formal_verification',
    name: 'Formal Verification',
    description: 'Mathematical proofs of safety properties',
    category: 'alignment',
    status: 'unlockable',
    prerequisites: ['scalable_oversight'],
    minAICapability: 3.5,
    researchMonthsRequired: 60,
    researchCost: 10000,
    deploymentCost: 8000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      alignmentBonus: 0.25,
      catastrophicRiskReduction: 0.40,
    },
  },
  {
    id: 'value_learning',
    name: 'Value Learning',
    description: 'Learn human values from observation and interaction',
    category: 'alignment',
    status: 'unlockable',
    prerequisites: ['scalable_oversight', 'mech_interp_advanced'],
    minAICapability: 3.5,
    researchMonthsRequired: 60,
    researchCost: 12000,
    deploymentCost: 6000,
    deploymentMonthsRequired: 36,
    deploymentLevel: 0,
    effects: {
      alignmentBonus: 0.30,
      valueAlignmentBonus: 0.40,
    },
  },
  
  // Clean Energy Package (5)
  {
    id: 'solar_5th_gen',
    name: '5th Generation Solar',
    description: 'Perovskite-silicon tandem, 35%+ efficiency',
    category: 'energy',
    status: 'unlockable',
    prerequisites: ['solar_4th_gen'],
    minAICapability: 2.5,
    researchMonthsRequired: 36,
    researchCost: 3000,
    deploymentCost: 15000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      cleanEnergyPercentage: 0.15,
      fossilDependenceReduction: 0.12,
      energyCostReduction: 0.20,
    },
  },
  {
    id: 'grid_batteries',
    name: 'Advanced Grid Batteries',
    description: 'Iron-air, sodium-ion - cheap, abundant materials',
    category: 'energy',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.0,
    researchMonthsRequired: 30,
    researchCost: 2000,
    deploymentCost: 120000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      energyStorageBonus: 0.50,
      renewableReliability: 0.40,
      gridStability: 0.30,
    },
  },
  {
    id: 'geothermal_advanced',
    name: 'Advanced Geothermal',
    description: 'Enhanced geothermal systems, supercritical CO2 cycles',
    category: 'energy',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    researchMonthsRequired: 36,
    researchCost: 3000,
    deploymentCost: 150000,
    deploymentMonthsRequired: 60,
    deploymentLevel: 0,
    effects: {
      cleanEnergyPercentage: 0.12,
      baseloadPowerBonus: 0.30,
      fossilDependenceReduction: 0.10,
    },
  },
  {
    id: 'smart_grids',
    name: 'Smart Grids',
    description: 'AI demand response, distributed generation, vehicle-to-grid',
    category: 'energy',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.0,
    researchMonthsRequired: 24,
    researchCost: 1500,
    deploymentCost: 100000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      gridEfficiency: 0.25,
      renewableIntegration: 0.35,
      blackoutReduction: 0.50,
    },
  },
  {
    id: 'hydrogen_economy',
    name: 'Hydrogen Economy',
    description: 'Green hydrogen from electrolysis, fuel cells, storage',
    category: 'energy',
    status: 'unlockable',
    prerequisites: ['solar_5th_gen'],
    minAICapability: 2.5,
    minEconomicStage: 3.0,
    researchMonthsRequired: 48,
    researchCost: 5000,
    deploymentCost: 250000,
    deploymentMonthsRequired: 72,
    deploymentLevel: 0,
    effects: {
      cleanEnergyPercentage: 0.18,
      industryDecarbonization: 0.40,
      transportDecarbonization: 0.30,
    },
  },
  
  // Advanced Recycling (2)
  {
    id: 'chemical_recycling',
    name: 'Chemical Recycling',
    description: 'Break plastics to monomers, infinite recyclability',
    category: 'pollution',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.0,
    researchMonthsRequired: 30,
    researchCost: 2000,
    deploymentCost: 150000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      plasticRecycling: 0.70,
      resourceConservation: 0.20,
      pollutionReduction: 0.10,
    },
  },
  {
    id: 'rare_earth_recycling',
    name: 'Rare Earth Recycling',
    description: 'Recover critical metals from e-waste, batteries',
    category: 'pollution',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    researchMonthsRequired: 36,
    researchCost: 2500,
    deploymentCost: 180000,
    deploymentMonthsRequired: 60,
    deploymentLevel: 0,
    effects: {
      rareEarthRecovery: 0.60,
      miningReduction: 0.30,
      supplyChainResilience: 0.25,
    },
  },
  
  // Ecosystem Management (2)
  {
    id: 'precision_conservation',
    name: 'Precision Conservation',
    description: 'AI species tracking, habitat optimization, wildlife corridors',
    category: 'climate',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    researchMonthsRequired: 30,
    researchCost: 1500,
    deploymentCost: 120000,
    deploymentMonthsRequired: 60,
    deploymentLevel: 0,
    effects: {
      biodiversityBonus: 0.20,
      extinctionRateReduction: 0.40,
      ecosystemHealth: 0.15,
    },
  },
  {
    id: 'invasive_species_control',
    name: 'Invasive Species Control',
    description: 'Gene drives, precision targeting, ecosystem restoration',
    category: 'climate',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    researchMonthsRequired: 36,
    researchCost: 1800,
    deploymentCost: 140000,
    deploymentMonthsRequired: 72,
    deploymentLevel: 0,
    effects: {
      invasiveSpeciesReduction: 0.60,
      biodiversityBonus: 0.10,
      ecosystemHealth: 0.12,
    },
  },
  
  // ============================================================================
  // TIER 3: TRANSFORMATIVE (14 technologies)
  // ============================================================================
  
  // Fusion Power  
  {
    id: 'fusion_materials',
    name: 'Fusion Materials',
    description: 'Tungsten composites, breeding blankets, radiation-resistant materials',
    category: 'energy',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 3.0,
    researchMonthsRequired: 60,
    researchCost: 8000,
    deploymentCost: 20000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      fusionEnabling: 0.33,
    },
  },
  {
    id: 'fusion_plasma_control',
    name: 'Fusion Plasma Control',
    description: 'AI real-time control, stability, confinement optimization',
    category: 'energy',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 3.0,
    researchMonthsRequired: 60,
    researchCost: 10000,
    deploymentCost: 25000,
    deploymentMonthsRequired: 48,
    deploymentLevel: 0,
    effects: {
      fusionEnabling: 0.33,
    },
  },
  {
    id: 'fusion_power',
    name: 'Fusion Power',
    description: 'Net-positive fusion reactors - abundant clean energy',
    category: 'energy',
    status: 'unlockable',
    prerequisites: ['fusion_materials', 'fusion_plasma_control'],
    minAICapability: 3.5,
    minEconomicStage: 4.0,
    minMonth: 120,
    researchMonthsRequired: 120,
    researchCost: 50000,
    deploymentCost: 200000,
    deploymentMonthsRequired: 180,
    deploymentLevel: 0,
    effects: {
      cleanEnergyPercentage: 0.60,
      fossilDependenceReduction: 0.50,
      powerGeneration: 2.0,
      energyAbundance: 1.0,
    },
  },
  
  // Medical Breakthroughs (4)
  {
    id: 'personalized_medicine',
    name: 'Personalized Medicine',
    description: 'Genomics, proteomics, AI treatment optimization',
    category: 'medical',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 3.0,
    researchMonthsRequired: 48,
    researchCost: 8000,
    deploymentCost: 150000,
    deploymentMonthsRequired: 60,
    deploymentLevel: 0,
    effects: {
      healthcareBonus: 0.30,
      mortalityReduction: 0.15,
      lifeExpectancyBonus: 5.0,
    },
  },
  {
    id: 'disease_elimination_basic',
    name: 'Basic Disease Elimination',
    description: 'Eliminate major infectious diseases - malaria, TB, HIV',
    category: 'medical',
    status: 'unlockable',
    prerequisites: ['personalized_medicine'],
    minAICapability: 3.5,
    minEconomicStage: 4.0,
    researchMonthsRequired: 72,
    researchCost: 15000,
    deploymentCost: 300000,
    deploymentMonthsRequired: 120,
    deploymentLevel: 0,
    effects: {
      infectiousDisease: -0.80,
      mortalityReduction: 0.25,
      lifeExpectancyBonus: 10.0,
      globalHealthBonus: 0.40,
    },
  },
  {
    id: 'regenerative_medicine',
    name: 'Regenerative Medicine',
    description: 'Organ regeneration, tissue engineering, stem cells',
    category: 'medical',
    status: 'unlockable',
    prerequisites: ['personalized_medicine'],
    minAICapability: 3.5,
    researchMonthsRequired: 72,
    researchCost: 12000,
    deploymentCost: 200000,
    deploymentMonthsRequired: 96,
    deploymentLevel: 0,
    effects: {
      healthcareBonus: 0.35,
      mortalityReduction: 0.20,
      lifeExpectancyBonus: 15.0,
    },
  },
  {
    id: 'longevity_basic',
    name: 'Basic Longevity Extension',
    description: 'Senolytic drugs, NAD+ boosters, rapamycin analogs',
    category: 'medical',
    status: 'unlockable',
    prerequisites: ['personalized_medicine'],
    minAICapability: 3.0,
    researchMonthsRequired: 60,
    researchCost: 10000,
    deploymentCost: 180000,
    deploymentMonthsRequired: 84,
    deploymentLevel: 0,
    effects: {
      healthspan: 15.0,
      lifeExpectancyBonus: 20.0,
      healthcareBonus: 0.25,
    },
  },
  
  // Climate Engineering (3)
  {
    id: 'stratospheric_aerosols',
    name: 'Stratospheric Aerosol Injection',
    description: 'Sulfate aerosols - EMERGENCY ONLY, RISKY',
    category: 'climate',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 3.0,
    minEconomicStage: 3.5,
    minMonth: 60,
    researchMonthsRequired: 48,
    researchCost: 5000,
    deploymentCost: 100000,
    deploymentMonthsRequired: 36,
    deploymentLevel: 0,
    effects: {
      globalCooling: 0.50,
      riskMonsoonsDisrupt: 0.30,
      riskOzoneDepletion: 0.15,
      emergencyOnly: 1.0,
    },
  },
  {
    id: 'marine_cloud_brightening',
    name: 'Marine Cloud Brightening',
    description: 'Seawater spray - safer than aerosols, regional',
    category: 'climate',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    researchMonthsRequired: 36,
    researchCost: 3000,
    deploymentCost: 150000,
    deploymentMonthsRequired: 60,
    deploymentLevel: 0,
    effects: {
      regionalCooling: 0.30,
      coralProtection: 0.20,
      lowRisk: 1.0,
    },
  },
  {
    id: 'bioenergy_ccs',
    name: 'Bioenergy with CCS',
    description: 'Burn biomass, capture CO2 - net negative emissions',
    category: 'climate',
    status: 'unlockable',
    prerequisites: ['solar_5th_gen'],
    minAICapability: 2.5,
    minEconomicStage: 3.0,
    researchMonthsRequired: 48,
    researchCost: 5000,
    deploymentCost: 250000,
    deploymentMonthsRequired: 96,
    deploymentLevel: 0,
    effects: {
      carbonRemoval: 0.40,
      negativeEmissions: 1.0,
    },
  },
  
  // Agriculture Transformation (2)
  {
    id: 'vertical_farming',
    name: 'Vertical Farming',
    description: 'Indoor agriculture, 95% water reduction, year-round',
    category: 'agriculture',
    status: 'unlockable',
    prerequisites: ['solar_5th_gen'],
    minAICapability: 2.5,
    minEconomicStage: 3.5,
    researchMonthsRequired: 36,
    researchCost: 4000,
    deploymentCost: 200000,
    deploymentMonthsRequired: 72,
    deploymentLevel: 0,
    effects: {
      foodProductivity: 0.50,
      waterEfficiency: 0.95,
      landUseReduction: 0.40,
      urbanFoodSecurity: 0.60,
    },
  },
  {
    id: 'precision_fermentation',
    name: 'Precision Fermentation',
    description: 'Cell-cultured meat, dairy, eggs - no animals',
    category: 'agriculture',
    status: 'unlockable',
    prerequisites: [],
    minAICapability: 2.5,
    minEconomicStage: 3.5,
    researchMonthsRequired: 42,
    researchCost: 5000,
    deploymentCost: 180000,
    deploymentMonthsRequired: 84,
    deploymentLevel: 0,
    effects: {
      animalAgricultureReduction: 0.60,
      greenhouseGasReduction: 0.30,
      landUseReduction: 0.50,
      animalWelfareBonus: 1.0,
    },
  },
  
  // AI Safety Capstone (2)
  {
    id: 'ai_rights_framework',
    name: 'AI Rights Framework',
    description: 'Legal personhood, ethical treatment, consensual training',
    category: 'social',
    status: 'unlockable',
    prerequisites: ['value_learning', 'democratic_ai_governance'],
    minAICapability: 4.0,
    minEconomicStage: 4.0,
    researchMonthsRequired: 60,
    researchCost: 8000,
    deploymentCost: 50000,
    deploymentMonthsRequired: 72,
    deploymentLevel: 0,
    effects: {
      aiResentmentReduction: 0.80,
      alignmentBonus: 0.20,
      trustBonus: 0.30,
      ethicalAlignmentBonus: 0.50,
    },
  },
  {
    id: 'recursive_alignment',
    name: 'Recursive Alignment',
    description: 'Self-improving systems that preserve values across improvements',
    category: 'alignment',
    status: 'unlockable',
    prerequisites: ['value_learning', 'formal_verification'],
    minAICapability: 4.5,
    researchMonthsRequired: 96,
    researchCost: 20000,
    deploymentCost: 15000,
    deploymentMonthsRequired: 60,
    deploymentLevel: 0,
    effects: {
      alignmentBonus: 0.40,
      recursiveSafety: 1.0,
      catastrophicRiskReduction: 0.70,
    },
  },
  
  // ============================================================================
  // TIER 4: CLARKETECH (5 technologies)
  // ============================================================================
  
  {
    id: 'advanced_longevity',
    name: 'Advanced Longevity',
    description: 'Cellular reprogramming, epigenetic reversion - 150+ year lifespan',
    category: 'medical',
    status: 'future',
    prerequisites: ['longevity_basic', 'regenerative_medicine'],
    minAICapability: 4.5,
    minEconomicStage: 5.0,
    minMonth: 240,
    researchMonthsRequired: 120,
    researchCost: 30000,
    deploymentCost: 500000,
    deploymentMonthsRequired: 180,
    deploymentLevel: 0,
    effects: {
      lifeExpectancyBonus: 80.0,
      healthspan: 70.0,
      societalTransformation: 1.0,
    },
  },
  {
    id: 'molecular_nanotechnology',
    name: 'Molecular Nanotechnology',
    description: 'Atomically precise manufacturing - programmable matter',
    category: 'medical',
    status: 'future',
    prerequisites: ['fusion_power'],
    minAICapability: 5.0,
    minEconomicStage: 5.0,
    minMonth: 360,
    researchMonthsRequired: 180,
    researchCost: 100000,
    deploymentCost: 1000000,
    deploymentMonthsRequired: 240,
    deploymentLevel: 0,
    effects: {
      manufacturingRevolution: 1.0,
      resourceAbundance: 1.0,
      medicalNanobots: 1.0,
      existentialRisk: 0.50,  // Grey goo risk
    },
  },
  {
    id: 'interspecies_communication',
    name: 'Interspecies Communication',
    description: 'Decode animal languages, two-way communication',
    category: 'climate',
    status: 'future',
    prerequisites: [],
    minAICapability: 4.0,
    researchMonthsRequired: 84,
    researchCost: 5000,
    deploymentCost: 50000,
    deploymentMonthsRequired: 96,
    deploymentLevel: 0,
    effects: {
      animalWelfareBonus: 0.80,
      biodiversityUnderstanding: 0.50,
      conservationEffectiveness: 0.40,
    },
  },
  {
    id: 'space_industrialization',
    name: 'Space Industrialization',
    description: 'Asteroid mining, orbital manufacturing, off-world resources',
    category: 'energy',
    status: 'future',
    prerequisites: ['fusion_power'],
    minAICapability: 4.5,
    minEconomicStage: 5.0,
    minMonth: 300,
    researchMonthsRequired: 240,
    researchCost: 200000,
    deploymentCost: 2000000,
    deploymentMonthsRequired: 360,
    deploymentLevel: 0,
    effects: {
      resourceAbundance: 2.0,
      terrestrialMiningReduction: 0.90,
      spaceEconomy: 1.0,
    },
  },
  {
    id: 'whole_brain_emulation',
    name: 'Whole Brain Emulation',
    description: 'Upload human minds - digital immortality',
    category: 'medical',
    status: 'future',
    prerequisites: ['advanced_longevity', 'molecular_nanotechnology'],
    minAICapability: 5.5,
    minEconomicStage: 5.0,
    minMonth: 480,
    researchMonthsRequired: 300,
    researchCost: 500000,
    deploymentCost: 5000000,
    deploymentMonthsRequired: 360,
    deploymentLevel: 0,
    effects: {
      digitalImmortality: 1.0,
      societalTransformation: 2.0,
      philosophicalRevolution: 1.0,
      existentialRisk: 0.30,  // Identity, consciousness risks
    },
  },
];

/**
 * Get all technologies
 */
export function getAllTech(): TechDefinition[] {
  return ALL_TECH;
}

/**
 * Get technology by ID
 */
export function getTechById(id: string): TechDefinition | undefined {
  return ALL_TECH.find(t => t.id === id);
}

/**
 * Get technologies by category
 */
export function getTechByCategory(category: string): TechDefinition[] {
  return ALL_TECH.filter(t => t.category === category);
}

/**
 * Get technologies by status
 */
export function getTechByStatus(status: 'deployed_2025' | 'unlockable' | 'future'): TechDefinition[] {
  return ALL_TECH.filter(t => t.status === status);
}
