/**
 * Phase Orchestrator - Phase 4
 *
 * Manages execution of simulation phases in correct order.
 * Each phase is a self-contained unit of work that can be tested independently.
 */

import { GameState, GameEvent } from '@/types/game';
import { logger } from '../utils/asyncLogger';
import { stateValidator, type StateSnapshot } from '../utils/stateValidation';
import { buildSimulationIndices, type SimulationIndices } from '../utils/simulationIndices';

/**
 * Random number generator function
 */
export type RNGFunction = () => number;

/**
 * Result of executing a phase
 */
export interface PhaseResult {
  /**
   * Events generated by this phase
   */
  events: GameEvent[];

  /**
   * Optional state replacement (for phases that return new state)
   */
  newState?: GameState;

  /**
   * Optional metadata about phase execution
   */
  metadata?: Record<string, any>;
}

/**
 * Represents a single simulation phase
 */
export interface SimulationPhase {
  /**
   * Unique identifier for this phase
   */
  readonly id: string;

  /**
   * Human-readable name for debugging
   */
  readonly name: string;

  /**
   * Execution order (lower numbers run first)
   * Use decimals for fine-grained ordering (e.g., 0.5, 1.0, 1.5)
   */
  readonly order: number;

  /**
   * Optional array of phase IDs that must execute BEFORE this phase
   *
   * Runtime validation ensures:
   * 1. Dependency phases have already executed this step
   * 2. Dependency phases have lower order numbers
   *
   * @example
   * // Any phase that modifies population AFTER mortality must declare dependency
   * readonly dependencies = ['bayesian_mortality_resolution'];
   *
   * // Phases can have multiple dependencies
   * readonly dependencies = ['climate_update', 'food_security_update'];
   */
  readonly dependencies?: readonly string[];

  /**
   * Execute this phase
   *
   * @param state - Current game state (may be mutated)
   * @param rng - Random number generator function
   * @param context - Optional context from previous phases
   * @returns Phase result with events and optional new state
   */
  execute(state: GameState, rng: RNGFunction, context?: PhaseContext): PhaseResult;
}

/**
 * Alias for backward compatibility
 */
export type Phase = SimulationPhase;

/**
 * Context shared between phases during a single step
 */
export interface PhaseContext {
  /**
   * Current month being simulated
   */
  month: number;

  /**
   * Logger instance (if available)
   */
  logger?: any;

  /**
   * Arbitrary data that phases can use to communicate
   */
  data: Map<string, any>;

  /**
   * Set of phase IDs that have executed in this step
   * Used for dependency validation
   */
  executedPhases: Set<string>;

  /**
   * Pre-built simulation indices for O(1) lookups (HIGH-1, Nov 20, 2025)
   *
   * Built once per step to eliminate O(n²) patterns. Provides:
   * - datacenterOwnership: dcId → orgId (eliminates 60,000 ops/step)
   * - agentMap: agentId → AIAgent (eliminates 500 ops/step)
   * - orgMap: orgId → Organization (general purpose)
   * - unlockedTech: Set<techId> (eliminates 710 ops/step)
   * - buildingOrgs: Set<orgId> (eliminates 40,000 ops/step)
   *
   * See: src/simulation/utils/simulationIndices.ts
   * Architecture Review: reviews/architecture_o2_bottlenecks_20251120.md
   */
  indices?: SimulationIndices;
}

/**
 * Orchestrates simulation phases in correct order
 */
export class PhaseOrchestrator {
  private phases: SimulationPhase[] = [];
  private sorted: boolean = false;

  // PERFORMANCE INSTRUMENTATION (Oct 28, 2025)
  // ENHANCED (Nov 12, 2025): Track min/max/p95 for better analysis
  // MEMORY LEAK FIX (Nov 15, 2025): Use Welford's algorithm for O(1) memory per phase
  // Previous: Stored 1000 samples × 95 phases = 760KB per simulation
  // Current: ~120 bytes per phase (6 numbers) = 11KB total for 95 phases
  /**
   * Maximum samples to keep per phase for p95 calculation (reservoir sampling).
   * Keeps 100 randomly selected samples for p95 estimation.
   */
  private static readonly MAX_PHASE_SAMPLES = 1000;
  /**
   * Maximum step timings to keep.
   * Keeps last 1200 steps = 100 years of simulation.
   * Prevents memory leak in long-running Monte Carlo (N=100 × 1200 steps = 120K entries → 1200 entries).
   */
  private static readonly MAX_STEP_TIMINGS = 1200;

  private phaseTimings: Map<string, {
    totalMs: number;
    callCount: number;
    minMs: number;
    maxMs: number;
    mean: number;        // Welford's algorithm: incremental mean
    m2: number;          // Welford's algorithm: sum of squared deviations (for variance)
  }> = new Map();
  private enableTiming: boolean = false;
  private slowPhaseThresholdMs: number = 10;  // Warn on phases >10ms
  private stepTimings: { month: number; totalMs: number }[] = [];  // Per-step totals

  /**
   * Register a phase
   */
  registerPhase(phase: SimulationPhase): void {
    this.phases.push(phase);
    this.sorted = false; // Mark as needing re-sort
  }

  /**
   * Register multiple phases at once
   */
  registerPhases(phases: SimulationPhase[]): void {
    this.phases.push(...phases);
    this.sorted = false;
  }

  /**
   * Execute all phases in order
   *
   * @param state - Game state (will be mutated)
   * @param rng - Random number generator
   * @param context - Optional context (created if not provided)
   * @returns All events generated by phases
   */
  executeAll(state: GameState, rng: RNGFunction, context?: PhaseContext): GameEvent[] {
    // Update logger with current simulation month (for yearly batching)
    logger.setSimulationMonth(state.currentMonth);

    // Ensure phases are sorted by order
    if (!this.sorted) {
      this.sortPhases();
    }

    // Create context if not provided
    const ctx: PhaseContext = context || {
      month: state.currentMonth,
      data: new Map(),
      executedPhases: new Set()
    };

    // BUILD SIMULATION INDICES (HIGH-1, Nov 20, 2025)
    // Pre-build O(1) lookup structures to eliminate O(n²) patterns
    // Impact: 98% reduction in operations (101,210 → 2,000 per step)
    // See: reviews/architecture_o2_bottlenecks_20251120.md
    ctx.indices = buildSimulationIndices(state);

    const allEvents: GameEvent[] = [];
    const stepStartTime = this.enableTiming ? performance.now() : 0;

    for (const phase of this.phases) {
      try {
        // PHASE DEPENDENCY VALIDATION (Oct 28, 2025)
        // Prevent race conditions like BayesianMortality → CountryPopulation bug
        if (phase.dependencies && phase.dependencies.length > 0) {
          for (const depId of phase.dependencies) {
            if (!ctx.executedPhases.has(depId)) {
              // Find the dependency phase to get its order number
              const depPhase = this.phases.find(p => p.id === depId);
              const depOrder = depPhase ? depPhase.order : 'unknown';

              throw new Error(
                `❌ PHASE DEPENDENCY VIOLATION: ${phase.name} (${phase.id})\n` +
                `   Requires phase: ${depId} (order: ${depOrder})\n` +
                `   Current phase order: ${phase.order}\n` +
                `   Month: ${state.currentMonth}\n` +
                `\n` +
                `   This phase declares a dependency on '${depId}' but that phase has not\n` +
                `   executed yet this step. Check phase order numbers or remove the dependency.\n` +
                `\n` +
                `   Executed phases so far: ${Array.from(ctx.executedPhases).join(', ')}`
              );
            }
          }
        }

        // STATE VALIDATION (Nov 15, 2025) - HIGH-3 fix
        // Pre-condition: Validate state BEFORE phase executes
        const preSnapshot = stateValidator.validatePreCondition(state, phase.name);

        // PERFORMANCE INSTRUMENTATION (Oct 28, 2025)
        const startTime = this.enableTiming ? performance.now() : 0;

        const result = phase.execute(state, rng, ctx);

        // STATE VALIDATION (Nov 15, 2025) - HIGH-3 fix
        // Post-condition: Validate state AFTER phase executes
        stateValidator.validatePostCondition(state, phase.name, preSnapshot);

        // PERFORMANCE INSTRUMENTATION (Oct 28, 2025)
        // ENHANCED (Nov 12, 2025): Track min/max/p95, warn on slow phases
        // MEMORY LEAK FIX (Nov 15, 2025): Use Welford's algorithm for O(1) memory
        if (this.enableTiming) {
          const elapsed = performance.now() - startTime;
          const existing = this.phaseTimings.get(phase.name) || {
            totalMs: 0,
            callCount: 0,
            minMs: Infinity,
            maxMs: -Infinity,
            mean: 0,
            m2: 0
          };

          // Welford's algorithm for incremental mean and variance
          // See: Knuth TAOCP vol 2, 3rd edition, page 232
          const newCount = existing.callCount + 1;
          const delta = elapsed - existing.mean;
          const newMean = existing.mean + delta / newCount;
          const delta2 = elapsed - newMean;
          const newM2 = existing.m2 + delta * delta2;

          this.phaseTimings.set(phase.name, {
            totalMs: existing.totalMs + elapsed,
            callCount: existing.callCount + 1,
            minMs: Math.min(existing.minMs, elapsed),
            maxMs: Math.max(existing.maxMs, elapsed),
            mean: newMean,
            m2: newM2
          });

          // Warn on slow phases (>10ms threshold)
          if (elapsed > this.slowPhaseThresholdMs) {
            console.log(`⚠️  [TIMING] Month ${state.currentMonth}: ${phase.name} took ${elapsed.toFixed(2)}ms (threshold: ${this.slowPhaseThresholdMs}ms)`);
          }
        }

        // Collect events
        if (result.events && result.events.length > 0) {
          allEvents.push(...result.events);
        }

        // Handle state replacement (some phases return new state)
        if (result.newState) {
          // Copy properties from new state to current state
          Object.assign(state, result.newState);
        }

        // Store metadata in context for later phases
        if (result.metadata) {
          ctx.data.set(phase.id, result.metadata);
        }

        // Mark this phase as executed (for dependency tracking)
        ctx.executedPhases.add(phase.id);

        // DETERMINISM DEBUG (Nov 5, 2025): Track AI capability checksum after EACH phase
        // Performance fix (Nov 20, 2025): Use performance config for checksum logging
        // This helps identify which phase causes divergence in deterministic runs
        const { getPerformanceConfig } = require('../config/performanceConfig');
        const perfConfig = getPerformanceConfig();

        if (perfConfig.deterministicChecksums && state.currentMonth < perfConfig.deterministicDebugMonths) {
          const aiCapabilityChecksum = state.aiAgents.reduce((sum, ai) => sum + ai.capability, 0);
          console.log(`[DET] Month ${state.currentMonth} After ${phase.name}: AI capability sum = ${aiCapabilityChecksum.toFixed(10)}`);
        }

        // DEBUG (Oct 28, 2025): Check population integrity after each phase
        if (isNaN(state.humanPopulationSystem.population)) {
          console.error(`\n❌ Population became NaN after phase "${phase.name}" (${phase.id})`);
          console.error(`   Month: ${state.currentMonth}`);
          console.error(`   Phase order: ${phase.order}`);
          throw new Error(`Phase "${phase.name}" corrupted population to NaN`);
        }
      } catch (error) {
        console.error(`\n❌ FATAL ERROR in phase "${phase.name}" (${phase.id}):`, error);
        console.error(`   Month: ${state.currentMonth}`);
        console.error(`   This error will halt the simulation to prevent invalid state propagation.`);

        // FIX (Oct 26, 2025): Re-throw to fail loudly - defensive fallback was masking bugs
        // Previous behavior: silently continued, causing paradigm scores to stay at 50.0
        // New behavior: throw immediately so bugs can't hide
        throw error;
      }
    }

    // PERFORMANCE INSTRUMENTATION (Nov 12, 2025): Log step total
    // MEMORY LEAK FIX (Nov 15, 2025): Sliding window for step timings (100 most recent)
    if (this.enableTiming) {
      const stepElapsed = performance.now() - stepStartTime;

      // Keep only last MAX_STEP_TIMINGS (1200) to prevent memory growth
      this.stepTimings.push({ month: state.currentMonth, totalMs: stepElapsed });
      if (this.stepTimings.length > PhaseOrchestrator.MAX_STEP_TIMINGS) {
        this.stepTimings = this.stepTimings.slice(-PhaseOrchestrator.MAX_STEP_TIMINGS);
      }

      // Log step summary (minimal overhead)
      if (stepElapsed > 50) {  // Only log if step took >50ms
        console.log(`📊 [TIMING] Month ${state.currentMonth} - Total: ${stepElapsed.toFixed(1)}ms`);
      }
    }

    // PHYSICAL CONSTRAINTS VALIDATION (Dec 1, 2025) - Development mode only
    // Validates state stays within physically plausible bounds (climate, population, energy, food)
    // Catches impossible values early before they cascade into NaN or unrealistic outcomes
    if (process.env.NODE_ENV === 'development') {
      const { validatePhysicalConstraints } = require('../utils/physicalConstraints');
      try {
        validatePhysicalConstraints(state, state.currentMonth);
      } catch (error) {
        console.error(`\n❌ PHYSICAL CONSTRAINT VIOLATION after all phases:`);
        console.error(`   Month: ${state.currentMonth}`);
        console.error(`   ${error instanceof Error ? error.message : String(error)}`);
        throw error;
      }
    }

    return allEvents;
  }

  /**
   * Get execution order (for debugging/documentation)
   */
  getExecutionOrder(): string[] {
    if (!this.sorted) {
      this.sortPhases();
    }
    return this.phases.map(p => `[${p.order}] ${p.name} (${p.id})`);
  }

  /**
   * Get phase count
   */
  getPhaseCount(): number {
    return this.phases.length;
  }

  /**
   * Get phase by ID
   */
  getPhase(id: string): SimulationPhase | undefined {
    return this.phases.find(p => p.id === id);
  }

  /**
   * Clear all registered phases (useful for testing)
   */
  clear(): void {
    this.phases = [];
    this.sorted = false;
  }

  /**
   * Validate all phase dependencies WITHOUT executing
   *
   * CRITICAL-2 FIX (Nov 10, 2025): Explicit validation method to catch
   * circular dependencies before first execution.
   *
   * Call this after registering all phases to validate the dependency graph:
   * ```typescript
   * orchestrator.registerPhases(ALL_PHASES);
   * orchestrator.validate(); // Throws if circular dependencies
   * ```
   *
   * @throws {Error} If circular dependency, missing dependency, or order violation detected
   */
  validate(): void {
    this.validateDependencies();
  }

  /**
   * Sort phases by order
   */
  private sortPhases(): void {
    // CIRCULAR DEPENDENCY DETECTION (Nov 6, 2025)
    // Validate dependencies before sorting to catch configuration errors early
    this.validateDependencies();

    this.phases.sort((a, b) => {
      // Primary sort: by order
      if (a.order !== b.order) {
        return a.order - b.order;
      }
      // Secondary sort: by name (for stability)
      return a.name.localeCompare(b.name);
    });
    this.sorted = true;
  }

  /**
   * Validate phase dependencies for circular references and ordering constraints
   *
   * Detects:
   * 1. Circular dependencies (A → B → C → A)
   * 2. Invalid order numbers (dependency has higher order than dependent)
   * 3. Missing phase references
   *
   * @throws {Error} If circular dependency or invalid ordering detected
   */
  private validateDependencies(): void {
    // Build phase lookup map
    const phaseMap = new Map<string, SimulationPhase>();
    for (const phase of this.phases) {
      phaseMap.set(phase.id, phase);
    }

    // Detect circular dependencies using depth-first search
    const visited = new Set<string>();
    const recursionStack = new Set<string>();

    const detectCycle = (phaseId: string, path: string[]): void => {
      if (recursionStack.has(phaseId)) {
        // Found a cycle - build error message with full path
        const cycleStart = path.indexOf(phaseId);
        const cyclePath = [...path.slice(cycleStart), phaseId];
        const cycleDescription = cyclePath.map(id => {
          const p = phaseMap.get(id);
          return p ? `${p.name} (${id}, order ${p.order})` : id;
        }).join(' → ');

        throw new Error(
          `❌ CIRCULAR DEPENDENCY DETECTED\n\n` +
          `   Cycle: ${cycleDescription}\n\n` +
          `   This creates an impossible ordering constraint. Phase dependencies must form\n` +
          `   a directed acyclic graph (DAG). Review the dependency declarations in these\n` +
          `   phases and remove the circular reference.\n`
        );
      }

      if (visited.has(phaseId)) {
        return; // Already processed this branch
      }

      visited.add(phaseId);
      recursionStack.add(phaseId);
      path.push(phaseId);

      const phase = phaseMap.get(phaseId);
      if (phase?.dependencies) {
        for (const depId of phase.dependencies) {
          // Check if dependency phase exists
          if (!phaseMap.has(depId)) {
            throw new Error(
              `❌ INVALID PHASE DEPENDENCY\n\n` +
              `   Phase: ${phase.name} (${phase.id}, order ${phase.order})\n` +
              `   Missing dependency: ${depId}\n\n` +
              `   This phase declares a dependency on '${depId}' but no phase with that\n` +
              `   ID is registered. Check for typos or remove the dependency.\n`
            );
          }

          // CRITICAL-2 FIX (Nov 10, 2025): Check cycles BEFORE order violations
          // This gives clearer error messages (shows full cycle path)
          detectCycle(depId, [...path]);

          // Check ordering constraint (dependency must have lower order number)
          // Note: This runs AFTER cycle check so circular deps are caught first
          const depPhase = phaseMap.get(depId)!;
          if (depPhase.order >= phase.order) {
            throw new Error(
              `❌ PHASE DEPENDENCY ORDER VIOLATION\n\n` +
              `   Phase: ${phase.name} (${phase.id})\n` +
              `   Order: ${phase.order}\n` +
              `   Depends on: ${depPhase.name} (${depId})\n` +
              `   Dependency order: ${depPhase.order}\n\n` +
              `   Dependencies must have LOWER order numbers than the dependent phase.\n` +
              `   Either:\n` +
              `   1. Change order numbers: ${phase.id} order must be > ${depPhase.order}\n` +
              `   2. Remove the dependency if it's not needed\n`
            );
          }
        }
      }

      recursionStack.delete(phaseId);
    };

    // Check each phase for cycles
    for (const phase of this.phases) {
      if (!visited.has(phase.id)) {
        detectCycle(phase.id, []);
      }
    }
  }

  // PERFORMANCE INSTRUMENTATION (Oct 28, 2025)

  /**
   * Enable performance timing for all phases
   */
  enablePerformanceTiming(): void {
    this.enableTiming = true;
    this.phaseTimings.clear();
  }

  /**
   * Disable performance timing
   */
  disablePerformanceTiming(): void {
    this.enableTiming = false;
  }

  /**
   * Set slow phase threshold (PERFORMANCE INSTRUMENTATION Nov 12, 2025)
   */
  setSlowPhaseThreshold(thresholdMs: number): void {
    this.slowPhaseThresholdMs = thresholdMs;
  }

  /**
   * Get current slow phase threshold
   */
  getSlowPhaseThreshold(): number {
    return this.slowPhaseThresholdMs;
  }

  /**
   * Get phase timing statistics (ENHANCED Nov 12, 2025: includes min/max/stddev)
   */
  getPhaseTimings(): Map<string, {
    totalMs: number;
    callCount: number;
    minMs: number;
    maxMs: number;
    mean: number;
    m2: number;
  }> {
    return new Map(this.phaseTimings);
  }

  /**
   * Get per-step timing data
   * PERFORMANCE INSTRUMENTATION (Nov 12, 2025)
   */
  getStepTimings(): { month: number; totalMs: number }[] {
    return [...this.stepTimings];
  }

  /**
   * Print phase timing report to console
   * ENHANCED (Nov 12, 2025): Shows min/max/p95 stats
   */
  printPhaseTimings(): void {
    if (this.phaseTimings.size === 0) {
      console.log('\n⚠️  No timing data collected. Call enablePerformanceTiming() first.');
      return;
    }

    // Calculate standard deviation from Welford's m2
    const calculateStdDev = (m2: number, count: number): number => {
      if (count < 2) return 0;
      const variance = m2 / (count - 1);  // Sample variance
      return Math.sqrt(variance);
    };

    // Calculate p95 from array of samples (for step timings)
    const calculateP95 = (samples: number[]): number => {
      if (samples.length === 0) return 0;
      const sorted = [...samples].sort((a, b) => a - b);
      const index = Math.ceil(sorted.length * 0.95) - 1;
      return sorted[Math.max(0, index)];
    };

    const sorted = Array.from(this.phaseTimings.entries())
      .map(([name, data]) => ({
        phaseName: name,
        totalMs: data.totalMs,
        callCount: data.callCount,
        avgMs: data.totalMs / data.callCount,
        minMs: data.minMs,
        maxMs: data.maxMs,
        stdDevMs: calculateStdDev(data.m2, data.callCount)
      }))
      .sort((a, b) => b.totalMs - a.totalMs);

    console.log('\n📊 PHASE TIMING ANALYSIS');
    console.log('='.repeat(100));
    console.log(
      'Phase Name'.padEnd(30) +
      'Avg'.padStart(10) +
      'StdDev'.padStart(10) +
      'Max'.padStart(10) +
      'Min'.padStart(10) +
      'Total'.padStart(12) +
      'Calls'.padStart(8)
    );
    console.log('-'.repeat(100));

    let totalTime = 0;
    for (const timing of sorted) {
      totalTime += timing.totalMs;
      console.log(
        timing.phaseName.padEnd(30) +
        `${timing.avgMs.toFixed(2)}ms`.padStart(10) +
        `${timing.stdDevMs.toFixed(2)}ms`.padStart(10) +
        `${timing.maxMs.toFixed(2)}ms`.padStart(10) +
        `${timing.minMs.toFixed(2)}ms`.padStart(10) +
        `${timing.totalMs.toFixed(1)}ms`.padStart(12) +
        timing.callCount.toString().padStart(8)
      );
    }

    console.log('-'.repeat(100));
    console.log('TOTAL'.padEnd(30) + ' '.repeat(40) + `${totalTime.toFixed(1)}ms`.padStart(12));
    console.log('='.repeat(100));

    // Top 5 slowest phases
    console.log('\n🔴 TOP 5 SLOWEST PHASES (by total time):');
    sorted.slice(0, 5).forEach((timing, i) => {
      const pct = (timing.totalMs / totalTime * 100).toFixed(1);
      console.log(`  ${i + 1}. ${timing.phaseName}: ${timing.totalMs.toFixed(1)}ms (${pct}%)`);
    });

    // Step timing summary
    if (this.stepTimings.length > 0) {
      const stepTotals = this.stepTimings.map(s => s.totalMs);
      const avgStep = stepTotals.reduce((a, b) => a + b, 0) / stepTotals.length;
      const maxStep = Math.max(...stepTotals);
      const minStep = Math.min(...stepTotals);
      const p95Step = calculateP95(stepTotals);

      console.log('\n📊 PER-STEP TIMING SUMMARY:');
      console.log(`  Steps: ${this.stepTimings.length}`);
      console.log(`  Avg: ${avgStep.toFixed(2)}ms`);
      console.log(`  P95: ${p95Step.toFixed(2)}ms`);
      console.log(`  Max: ${maxStep.toFixed(2)}ms`);
      console.log(`  Min: ${minStep.toFixed(2)}ms`);
    }
  }

  /**
   * Reset phase timing statistics
   */
  resetPhaseTimings(): void {
    this.phaseTimings.clear();
    this.stepTimings = [];
  }

  /**
   * Export phase timings as CSV for analysis
   * PERFORMANCE INSTRUMENTATION (Nov 12, 2025)
   */
  exportPhaseTimingsCSV(): string {
    if (this.phaseTimings.size === 0) {
      return '';
    }

    // Calculate standard deviation from Welford's m2
    const calculateStdDev = (m2: number, count: number): number => {
      if (count < 2) return 0;
      const variance = m2 / (count - 1);  // Sample variance
      return Math.sqrt(variance);
    };

    const lines = ['Phase,Avg_ms,StdDev_ms,Max_ms,Min_ms,Total_ms,Calls'];

    for (const [name, data] of this.phaseTimings.entries()) {
      const avgMs = data.totalMs / data.callCount;
      const stdDevMs = calculateStdDev(data.m2, data.callCount);
      lines.push(
        `${name},${avgMs.toFixed(2)},${stdDevMs.toFixed(2)},${data.maxMs.toFixed(2)},${data.minMs.toFixed(2)},${data.totalMs.toFixed(1)},${data.callCount}`
      );
    }

    return lines.join('\n');
  }

  /**
   * Export phase timings as JSON for programmatic analysis
   * PERFORMANCE INSTRUMENTATION (Nov 12, 2025)
   */
  exportPhaseTimingsJSON(): string {
    if (this.phaseTimings.size === 0) {
      return '{}';
    }

    // Calculate standard deviation from Welford's m2
    const calculateStdDev = (m2: number, count: number): number => {
      if (count < 2) return 0;
      const variance = m2 / (count - 1);  // Sample variance
      return Math.sqrt(variance);
    };

    // Calculate p95 from array of samples (for step timings)
    const calculateP95 = (samples: number[]): number => {
      if (samples.length === 0) return 0;
      const sorted = [...samples].sort((a, b) => a - b);
      const index = Math.ceil(sorted.length * 0.95) - 1;
      return sorted[Math.max(0, index)];
    };

    const result: Record<string, any> = {
      phases: {},
      steps: this.stepTimings,
      summary: {
        totalPhases: this.phaseTimings.size,
        totalSteps: this.stepTimings.length
      }
    };

    for (const [name, data] of this.phaseTimings.entries()) {
      result.phases[name] = {
        totalMs: parseFloat(data.totalMs.toFixed(1)),
        callCount: data.callCount,
        avgMs: parseFloat((data.totalMs / data.callCount).toFixed(2)),
        minMs: parseFloat(data.minMs.toFixed(2)),
        maxMs: parseFloat(data.maxMs.toFixed(2)),
        stdDevMs: parseFloat(calculateStdDev(data.m2, data.callCount).toFixed(2))
      };
    }

    // Add step summary
    if (this.stepTimings.length > 0) {
      const stepTotals = this.stepTimings.map(s => s.totalMs);
      result.summary.steps = {
        avg: parseFloat((stepTotals.reduce((a, b) => a + b, 0) / stepTotals.length).toFixed(2)),
        min: parseFloat(Math.min(...stepTotals).toFixed(2)),
        max: parseFloat(Math.max(...stepTotals).toFixed(2)),
        p95: parseFloat(calculateP95(stepTotals).toFixed(2))
      };
    }

    return JSON.stringify(result, null, 2);
  }
}
