import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { Navigation } from "@/components/core/Navigation";
import { SimulationWorkerProvider } from "@/lib/contexts/SimulationWorkerContext";
=======
>>>>>>> 8e2778351 (Initial commit from Create Next App)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Superalignment to Utopia",
  description: "Research simulation: AI alignment to human flourishing pathways",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 8e2778351 (Initial commit from Create Next App)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <SimulationWorkerProvider>
          <div className="flex">
            <Navigation />
            <div className="ml-64 flex-1">
              {children}
            </div>
          </div>
        </SimulationWorkerProvider>
=======
        {children}
>>>>>>> 8e2778351 (Initial commit from Create Next App)
      </body>
    </html>
  );
}
