/**
 * ComputeAllocationPhase (4.0)
 *
 * Allocates compute to all AI agents at the start of each month.
 * Must run after compute growth and organization turns (so new
 * datacenters are available).
 *
 * **EXECUTION ORDER:** 4.0 (Early infrastructure, before AI lifecycle)
 * **DEPENDENCIES:** Requires compute infrastructure
 * **SIDE EFFECTS:**
 * - Sets allocatedCompute for all AI agents
 * - Updates compute availability
 */

import { GameState, SimulationPhase, PhaseResult, PhaseContext, RNGFunction } from '@/types/game';
import { setDeterministicRng } from '@/simulation/utils/deterministicRng';
import { assertFinite, assertDefined } from '@/simulation/utils/assertions';
import { allocateComputeGlobally } from '../../computeInfrastructure';
import { getTotalEffectiveCompute } from '../../computeInfrastructure';

export class ComputeAllocationPhase implements SimulationPhase {
  readonly id = 'compute-allocation';
  readonly name = 'Compute Allocation';
  readonly order = 3.0;
  readonly dependencies = ['compute-growth', 'organization-turns'];

  execute(state: GameState, rng: RNGFunction): PhaseResult {
    // Import and execute compute allocation
    setDeterministicRng(rng);// Validate compute infrastructure exists before allocation
    assertDefined(state.computeInfrastructure, {
      location: 'ComputeAllocationPhase.execute',
      valueName: 'computeInfrastructure',
      month: state.currentMonth,
    });

    // Validate total compute is finite (use helper function)const totalCompute = getTotalEffectiveCompute(state.computeInfrastructure);
    assertFinite(totalCompute, {
      location: 'ComputeAllocationPhase.execute',
      valueName: 'totalEffectiveCompute',
      month: state.currentMonth,
    });

    allocateComputeGlobally(state);

    // Validate allocation succeeded (all agents have compute assigned)
    for (const agent of state.aiAgents) {
      if (agent.lifecycleState === 'deployed_closed' || agent.lifecycleState === 'deployed_open' || agent.lifecycleState === 'training') {
        assertFinite(agent.allocatedCompute, {
          location: 'ComputeAllocationPhase.execute (post-allocation)',
          valueName: `agent[${agent.id}].allocatedCompute`,
          month: state.currentMonth,
          additionalInfo: { agentId: agent.id, lifecycleState: agent.lifecycleState },
        });
      }
    }

    // No events generated by allocation
    return { events: [] };
  }
}
