/**
 * ComputeGrowthPhase (5.0)
 *
 * Applies Moore's Law and algorithmic improvements to compute infrastructure.
 * This must run BEFORE allocation so efficiency multipliers are applied.
 *
 * **EXECUTION ORDER:** 5.0 (Very early, first in simulation step)
 * **DEPENDENCIES:** Requires compute infrastructure
 * **SIDE EFFECTS:**
 * - Updates compute efficiency multipliers
 * - Applies algorithmic progress
 */

import { GameState, SimulationPhase, PhaseResult, PhaseContext, RNGFunction } from '@/types/game';
import { setDeterministicRng } from '@/simulation/utils/deterministicRng';
import { assertFinite, assertDefined, assertInRange } from '@/simulation/utils/assertions';
import { applyComputeGrowth, getTotalEffectiveCompute } from '../../computeInfrastructure';

export class ComputeGrowthPhase implements SimulationPhase {
  readonly id = 'compute-growth';
  readonly name = 'Compute Growth (Moore\'s Law)';
  readonly order = 1.0;

  // DEPENDENCIES (Nov 15, 2025): No dependencies - reads/writes compute infrastructure only
  readonly dependencies = [] as const;

  execute(state: GameState, rng: RNGFunction): PhaseResult {
    // Import and execute compute growth
    setDeterministicRng(rng);// Validate compute infrastructure exists before growth
    assertDefined(state.computeInfrastructure, {
      location: 'ComputeGrowthPhase.execute',
      valueName: 'computeInfrastructure',
      month: state.currentMonth,
    });

    // Capture initial state for validation (use helper function)
    const initialTotalCompute = assertFinite(getTotalEffectiveCompute(state.computeInfrastructure), {
      location: 'ComputeGrowthPhase.execute (pre-growth)',
      valueName: 'totalEffectiveCompute',
      month: state.currentMonth,
    });

    applyComputeGrowth(state, rng);

    // Validate post-growth state (use helper function)
    const finalTotalCompute = assertFinite(getTotalEffectiveCompute(state.computeInfrastructure), {
      location: 'ComputeGrowthPhase.execute (post-growth)',
      valueName: 'totalEffectiveCompute',
      month: state.currentMonth,
    });

    // Validate efficiency multipliers are valid (unbounded - quantum/transformative tech can give 1000x+)
    // These accumulate multiplicatively over time (Moore's Law: ~2x every 2 years)
    assertFinite(state.computeInfrastructure.hardwareEfficiency, {
      location: 'ComputeGrowthPhase.execute (post-growth)',
      valueName: 'computeInfrastructure.hardwareEfficiency',
      month: state.currentMonth,
      additionalInfo: { note: 'Hardware efficiency accumulates multiplicatively - no upper bound (quantum computing could reach 1000x+)' },
    });

    assertFinite(state.computeInfrastructure.algorithmsEfficiency, {
      location: 'ComputeGrowthPhase.execute (post-growth)',
      valueName: 'computeInfrastructure.algorithmsEfficiency',
      month: state.currentMonth,
      additionalInfo: { note: 'Algorithmic efficiency accumulates multiplicatively - no upper bound' },
    });

    // No events generated by growth
    return { events: [] };
  }
}
