/**
 * ComputeAllocationPhase (4.0)
 *
 * Allocates compute to all AI agents at the start of each month.
 * Must run after compute growth and organization turns (so new
 * datacenters are available).
 *
 * **EXECUTION ORDER:** 4.0 (Early infrastructure, before AI lifecycle)
 * **DEPENDENCIES:** Requires compute infrastructure
 * **SIDE EFFECTS:**
 * - Sets allocatedCompute for all AI agents
 * - Updates compute availability
 */

import { SimulationPhase, PhaseResult } from '../PhaseOrchestrator';
import { GameState } from '@/types/game';
import { RNGFunction } from '@/types/rng';

export class ComputeAllocationPhase implements SimulationPhase {
  readonly id = 'compute-allocation';
  readonly name = 'Compute Allocation';
  readonly order = 3.0;

  execute(state: GameState, rng: RNGFunction): PhaseResult {
    // Import and execute compute allocation
    const { allocateComputeGlobally } = require('../../computeInfrastructure');

    allocateComputeGlobally(state);

    // No events generated by allocation
    return { events: [] };
  }
}
