#!/bin/bash
# MARCUS 3.0 Complete System Validation Script
# Validates all fixes from 6-hour debugging session
# Usage: ./test_marcus_complete.sh

set -e

# ============================================================================
# Load Environment Variables Securely (OWASP Compliant)
# ============================================================================
# Fallback chain: .env (runtime) -> .env.secrets (provisioning)
# Passwords never exposed in process listings or command line arguments

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

load_env_file() {
    local env_file="$1"
    if [ -f "$env_file" ]; then
        # Use set -a to auto-export all variables
        set -a
        source "$env_file"
        set +a
        return 0
    fi
    return 1
}

# Try loading .env first (generated by provisioning, contains runtime passwords)
if load_env_file "$PROJECT_DIR/.env"; then
    : # Success - using .env
# Fallback to .env.secrets (user-provided secrets, used during provisioning)
elif load_env_file "$PROJECT_DIR/.env.secrets"; then
    : # Success - using .env.secrets
else
    echo "⚠️  Warning: No .env or .env.secrets file found"
    echo "    Environment variables must be set manually"
fi

# ============================================================================
# Secure Database Connection Setup (OWASP Compliant)
# ============================================================================
# Uses .pgpass file to avoid exposing passwords in process listings

PGPASS_FILE="$HOME/.pgpass_test_$$"

setup_secure_db_connection() {
    if [ -n "$DATABASE_PASSWORD" ]; then
        # Create temporary .pgpass file (format: hostname:port:database:username:password)
        echo "${DATABASE_HOST:-localhost}:${DATABASE_PORT:-5432}:${DATABASE_NAME}:${DATABASE_USER}:${DATABASE_PASSWORD}" > "$PGPASS_FILE"
        chmod 600 "$PGPASS_FILE"
        export PGPASSFILE="$PGPASS_FILE"
    fi
}

cleanup_secure_db_connection() {
    if [ -f "$PGPASS_FILE" ]; then
        rm -f "$PGPASS_FILE"
    fi
}

# Setup secure connection
setup_secure_db_connection

# Cleanup on exit
trap cleanup_secure_db_connection EXIT

# Secure psql wrapper function
secure_psql() {
    psql -h "${DATABASE_HOST:-localhost}" -U "${DATABASE_USER}" -d "${DATABASE_NAME}" "$@"
}

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Test counters
TESTS_PASSED=0
TESTS_FAILED=0
TESTS_TOTAL=0

# Helper functions
print_header() {
    echo ""
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}"
}

print_test() {
    TESTS_TOTAL=$((TESTS_TOTAL + 1))
    echo -e "${YELLOW}[TEST $TESTS_TOTAL]${NC} $1"
}

print_pass() {
    TESTS_PASSED=$((TESTS_PASSED + 1))
    echo -e "${GREEN}✅ PASS:${NC} $1"
}

print_fail() {
    TESTS_FAILED=$((TESTS_FAILED + 1))
    echo -e "${RED}❌ FAIL:${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ️  INFO:${NC} $1"
}

# Phase 1: System Requirements
print_header "Phase 1: System Requirements"

print_test "Checking Node.js version"
if command -v node &> /dev/null; then
    NODE_VERSION=$(node --version)
    print_pass "Node.js installed: $NODE_VERSION"
else
    print_fail "Node.js not installed"
fi

print_test "Checking Python version"
if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version)
    print_pass "Python3 installed: $PYTHON_VERSION"
else
    print_fail "Python3 not installed"
fi

print_test "Checking PostgreSQL"
if command -v psql &> /dev/null; then
    PSQL_VERSION=$(psql --version)
    print_pass "PostgreSQL installed: $PSQL_VERSION"
else
    print_fail "PostgreSQL not installed"
fi

print_test "Checking Redis"
if command -v redis-cli &> /dev/null; then
    if redis-cli ping &> /dev/null; then
        print_pass "Redis running"
    else
        print_fail "Redis installed but not running"
    fi
else
    print_fail "Redis not installed"
fi

# Phase 2: Environment Variables
print_header "Phase 2: Environment Variables"

REQUIRED_ENV_VARS=(
    "DATABASE_HOST"
    "DATABASE_NAME"
    "DATABASE_USER"
    "DATABASE_PASSWORD"
    "REDIS_HOST"
    "JWT_SECRET"
)

for var in "${REQUIRED_ENV_VARS[@]}"; do
    print_test "Checking $var"
    if [ -n "${!var}" ]; then
        print_pass "$var is set"
    else
        print_fail "$var is not set"
    fi
done

# Phase 3: Database Schema
print_header "Phase 3: Database Schema Validation"

if [ -n "$DATABASE_HOST" ] && [ -n "$DATABASE_NAME" ] && [ -n "$DATABASE_USER" ]; then
    print_test "Testing database connection"
    if secure_psql -c "SELECT 1" &> /dev/null; then
        print_pass "Database connection successful"
        
        # Check for required tables
        REQUIRED_TABLES=("users" "citation_analyses" "agent_behaviors" "refresh_tokens" "auth_audit_log")
        for table in "${REQUIRED_TABLES[@]}"; do
            print_test "Checking table: $table"
            if secure_psql -c "\dt $table" | grep -q "$table"; then
                print_pass "Table $table exists"
            else
                print_fail "Table $table missing"
            fi
        done
        
        # Check for default admin user
        print_test "Checking default admin user"
        if secure_psql -c "SELECT COUNT(*) FROM users WHERE email='admin@marcus.local'" | grep -q "1"; then
            print_pass "Default admin user exists"
        else
            print_fail "Default admin user missing"
        fi
    else
        print_fail "Database connection failed"
    fi
else
    print_fail "Database environment variables not set, skipping schema checks"
fi

# Phase 4: Project Structure
print_header "Phase 4: Project Structure"

REQUIRED_FILES=(
    "src/platform/config/platformConfig.ts"
    "src/platform/database/pool.ts"
    "src/platform/auth/authService.ts"
    "src/platform/api/authRoutes.ts"
    "src/platform/agents/citation_integrity_agent.py"
    "src/platform/integration/citationAgentIntegration.ts"
    "src/platform/resilience/circuitBreaker.ts"
    "src/platform/utils/logger.ts"
    "ecosystem.config.js"
    "marcus-platform.service"
)

for file in "${REQUIRED_FILES[@]}"; do
    print_test "Checking file: $file"
    if [ -f "$file" ]; then
        print_pass "File exists: $file"
    else
        print_fail "File missing: $file"
    fi
done

# Phase 5: TypeScript Compilation
print_header "Phase 5: TypeScript Build Status"

print_test "Checking if TypeScript is compiled"
if [ -d "dist" ]; then
    print_pass "dist/ directory exists"
    
    print_test "Checking compiled startup script"
    if [ -f "dist/platform/startup.js" ]; then
        print_pass "Startup script compiled"
    else
        print_fail "Startup script not compiled (run: npm run build)"
    fi
else
    print_fail "dist/ directory missing (run: npm run build)"
fi

# Phase 6: Python Dependencies
print_header "Phase 6: Python Dependencies"

REQUIRED_PYTHON_PACKAGES=("anthropic" "psycopg2" "redis")

for package in "${REQUIRED_PYTHON_PACKAGES[@]}"; do
    print_test "Checking Python package: $package"
    if python3 -c "import $package" &> /dev/null; then
        print_pass "Package $package installed"
    else
        print_fail "Package $package missing (run: pip install $package)"
    fi
done

# Phase 7: Python Agent Functionality
print_header "Phase 7: Python Agent Validation"

print_test "Testing Python agent in demo mode"
if timeout 5 python3 src/platform/agents/citation_integrity_agent.py &> /dev/null; then
    print_pass "Python agent runs in demo mode"
else
    print_fail "Python agent failed in demo mode"
fi

print_test "Testing Python agent IPC mode (get_status)"
AGENT_RESPONSE=$(echo '{"type":"request","requestId":"test-1","method":"get_status","params":{}}' | timeout 5 python3 src/platform/agents/citation_integrity_agent.py agent_test 2>/dev/null | tail -1)
if echo "$AGENT_RESPONSE" | grep -q "response"; then
    print_pass "Python agent IPC mode works"
else
    print_fail "Python agent IPC mode failed"
fi

# Phase 8: API Endpoints (requires server running)
print_header "Phase 8: API Endpoint Testing"

print_info "Attempting to start server for testing..."

# Start server in background
if [ -f "dist/platform/startup.js" ]; then
    NODE_ENV=test timeout 10 node dist/platform/startup.js > /tmp/marcus_test_server.log 2>&1 &
    SERVER_PID=$!
    
    # Wait for server to start
    sleep 3
    
    print_test "Testing health endpoint"
    if curl -s http://localhost:3000/health | grep -q "healthy"; then
        print_pass "Health endpoint accessible"
    else
        print_fail "Health endpoint not accessible"
    fi
    
    print_test "Testing login endpoint"
    LOGIN_RESPONSE=$(curl -s -X POST http://localhost:3000/auth/login \
        -H "Content-Type: application/json" \
        -d '{"email":"admin@marcus.local","password":"SecurePassword123!"}')
    
    if echo "$LOGIN_RESPONSE" | grep -q "accessToken"; then
        print_pass "Login endpoint works"
    else
        print_fail "Login endpoint failed"
    fi
    
    # Cleanup
    kill $SERVER_PID 2>/dev/null || true
else
    print_fail "Cannot test API endpoints - server not built"
fi

# Phase 9: Process Supervision Configuration
print_header "Phase 9: Process Supervision"

print_test "Checking PM2 configuration"
if [ -f "ecosystem.config.js" ]; then
    if grep -q "marcus-platform" ecosystem.config.js; then
        print_pass "PM2 configuration valid"
    else
        print_fail "PM2 configuration malformed"
    fi
else
    print_fail "PM2 configuration missing"
fi

print_test "Checking systemd service unit"
if [ -f "marcus-platform.service" ]; then
    if grep -q "Description=MARCUS 3.0" marcus-platform.service; then
        print_pass "systemd service unit valid"
    else
        print_fail "systemd service unit malformed"
    fi
else
    print_fail "systemd service unit missing"
fi

# Phase 10: Documentation
print_header "Phase 10: Documentation Completeness"

REQUIRED_DOCS=(
    "docs/MARCUS_DEBUGGING_REPORT.md"
    "docs/MARCUS_DEBUGGING_TUTORIAL.md"
    "docs/MARCUS_IMPLEMENTATION_CHECKLIST.md"
)

for doc in "${REQUIRED_DOCS[@]}"; do
    print_test "Checking documentation: $doc"
    if [ -f "$doc" ]; then
        print_pass "Documentation exists: $doc"
    else
        print_fail "Documentation missing: $doc"
    fi
done

# Final Summary
print_header "Test Summary"

TESTS_TOTAL_ACTUAL=$((TESTS_PASSED + TESTS_FAILED))
PASS_RATE=$(awk "BEGIN {printf \"%.1f\", ($TESTS_PASSED/$TESTS_TOTAL_ACTUAL)*100}")

echo ""
echo -e "${BLUE}Total Tests Run:${NC} $TESTS_TOTAL_ACTUAL"
echo -e "${GREEN}Tests Passed:${NC} $TESTS_PASSED"
echo -e "${RED}Tests Failed:${NC} $TESTS_FAILED"
echo -e "${BLUE}Pass Rate:${NC} $PASS_RATE%"
echo ""

if [ $TESTS_FAILED -eq 0 ]; then
    echo -e "${GREEN}🎉 ALL TESTS PASSED! MARCUS 3.0 is ready for deployment.${NC}"
    exit 0
else
    echo -e "${RED}⚠️  Some tests failed. Review failures above and fix issues.${NC}"
    exit 1
fi
