apiVersion: v1
data:
  ENCRYPTION_KEY: UkVQTEFDRV9XSVRIXzMyX0JZVEVfS0VZ
  JWT_REFRESH_SECRET: UkVQTEFDRV9XSVRIX1NFQ1VSRV9WQUxVRQ==
  JWT_SECRET: QU9CQW51K01meTBJUTExNHF0TElzT1h0bndUM2dpUGNja1Zwd204aUZsND0=
  OAUTH_CLIENT_ID: ""
  OAUTH_CLIENT_SECRET: ""
  POSTGRES_PASSWORD: UkVQTEFDRV9XSVRIX1NFQ1VSRV9WQUxVRQ==
  POSTGRES_USER: bWFyY3VzX2FwcA==
  REDIS_PASSWORD: UkVQTEFDRV9XSVRIX1NFQ1VSRV9WQUxVRQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"marcus-secrets","namespace":"marcus-platform"},"stringData":{"ENCRYPTION_KEY":"REPLACE_WITH_32_BYTE_KEY","JWT_REFRESH_SECRET":"REPLACE_WITH_SECURE_VALUE","JWT_SECRET":"REPLACE_WITH_SECURE_VALUE","OAUTH_CLIENT_ID":"","OAUTH_CLIENT_SECRET":"","POSTGRES_PASSWORD":"REPLACE_WITH_SECURE_VALUE","POSTGRES_USER":"marcus_app","REDIS_PASSWORD":"REPLACE_WITH_SECURE_VALUE"},"type":"Opaque"}
  creationTimestamp: "2025-11-22T06:30:55Z"
  name: marcus-secrets
  namespace: marcus-platform
  resourceVersion: "1763876625153839003"
  uid: d312fb73-3b34-4735-bf4b-acb399efddf9
type: Opaque
